<?php

return [
	'key' => 'group_63857a99086a5',
	'title' => 'Home Banner Block',
	'fields' => array(
		array(
			'key' => 'field_63857d04e4d39',
			'label' => 'Text Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_63857aa1e4d34',
			'label' => 'Title',
			'name' => 'home-header_title',
			'type' => 'text',
			'instructions' => 'Add the header title here.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		// array(
		// 	'key' => 'field_63857ae2e4d35',
		// 	'label' => 'Subheading',
		// 	'name' => 'home-header_subheading',
		// 	'type' => 'text',
		// 	'instructions' => 'Add the subheading here.',
		// 	'required' => 0,
		// 	'conditional_logic' => 0,
		// 	'wrapper' => array(
		// 		'width' => '',
		// 		'class' => '',
		// 		'id' => '',
		// 	),
		// 	'default_value' => '',
		// 	'placeholder' => '',
		// 	'prepend' => '',
		// 	'append' => '',
		// 	'maxlength' => '',
		// ),
		array(
			'key' => 'field_63857b0ee4d36',
			'label' => 'Button One',
			'name' => 'home-header_button-one',
			'type' => 'link',
			'instructions' => 'Add the text and URL. for the first button here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '47',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_63857be1e4d37',
			'label' => 'Button Two',
			'name' => 'home-header_button-two',
			'type' => 'link',
			'instructions' => 'Add the text and URL for the second button here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_63857d32e4d3a',
			'label' => 'Background',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_63857c6be4d38',
			'label' => 'Banner Image',
			'name' => 'home-header_banner-image',
			'type' => 'image',
			'instructions' => 'Add the banner image here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		// array(
		// 	'key' => 'field_63857ae2e4d3512322',
		// 	'label' => 'Banner Video',
		// 	'name' => 'home-header_banner-video-text',
		// 	'type' => 'text',
		// 	'instructions' => 'Add the banner video here.',
		// 	'required' => 0,
		// 	'conditional_logic' => 0,
		// 	'wrapper' => array(
		// 		'width' => '',
		// 		'class' => '',
		// 		'id' => '',
		// 	),
		// 	'default_value' => '',
		// 	'placeholder' => '',
		// 	'prepend' => '',
		// 	'append' => '',
		// 	'maxlength' => '',
		// ),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/headerhome',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
];