version: '3.8'
#
# Container_name should not be modified, in order to modify the container names
# Adjust the APP_NAME variable in `.env`.
#
services:
  #
  # WordPress Web Server (PHP, Apache, etc)
  #
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_PREFIX: ${WP_DB_PREFIX}
    volumes:
      - ./html:/var/www/html

  #
  # Mariadb Database
  #
  db:
    container_name: ${APP_NAME:?err}-db
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - .data/mysql:/var/lib/mysql
      - .docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  #
  # Phpmyadmin Database Viewer Container
  #
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      UPLOAD_LIMIT: 1000M

  #
  # Gulp Task Runner
  #
  gulp:
    build:
      context: .
      dockerfile: .docker/build/Gulp/Dockerfile
    container_name: gulp
    volumes:
      - ./themesrc:/app
    command: gulp