<?php

return [
	'key' => 'group_749943ce375ed',
		'title' => 'Find Me A Bike Block',
		'fields' => array(
			array(
				'key' => 'field_749943ce39a7e',
				'label' => 'Text / Buttons',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_749943ce39a86',
				'label' => 'Heading',
				'name' => 'heading',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Add the header title here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_749944807cbd1',
				'label' => 'SubHeading',
				'name' => 'subheading',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Add the sub heading here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_749944977cbd2',
				'label' => 'Description',
				'name' => 'description',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => 'Add the header title here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
                    'value' => 'acf/findmeabikeblock',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
];