<?php
return [
    'key' => 'group_6476332c5c062',
    'title' => 'Product Category Showcase Block',
    'fields' => array(
        array(
            'key' => 'field_6476332c5e34c',
            'label' => 'Contents',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),

        array(
            'key' => 'field_6476332c5e999',
            'label' => 'Message',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => 'This is a global widget and it\'s recommended to add this block only once per page. <a href="/wp-admin/admin.php?page=sbm_theme_options_global_blocks" target="_blank">Click here</a> to edit the content. <strong>Options -> Global Blocks -> Product Category Showcase Block</strong>',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),

        // array(
        //     'key' => 'field_6476332c5e355',
        //     'label' => 'Heading',
        //     'name' => 'heading',
        //     'aria-label' => '',
        //     'type' => 'text',
        //     'instructions' => '',
        //     'required' => 0,
        //     'conditional_logic' => 0,
        //     'wrapper' => array(
        //         'width' => '',
        //         'class' => '',
        //         'id' => '',
        //     ),
        //     'default_value' => '',
        //     'maxlength' => '',
        //     'placeholder' => '',
        //     'prepend' => '',
        //     'append' => '',
        // ),
        // array(
        //     'key' => 'field_6476332c5e35d',
        //     'label' => 'Product Category Columns',
        //     'name' => 'product_category_columns',
        //     'aria-label' => '',
        //     'type' => 'repeater',
        //     'instructions' => '',
        //     'required' => 0,
        //     'conditional_logic' => 0,
        //     'wrapper' => array(
        //         'width' => '',
        //         'class' => '',
        //         'id' => '',
        //     ),
        //     'layout' => 'table',
        //     'pagination' => 0,
        //     'min' => 0,
        //     'max' => 0,
        //     'collapsed' => '',
        //     'button_label' => 'Add Row',
        //     'rows_per_page' => 20,
        //     'sub_fields' => array(
        //         array(
        //             'key' => 'field_6476332c60236',
        //             'label' => 'Product Category image',
        //             'name' => 'product_category_image',
        //             'aria-label' => '',
        //             'type' => 'image',
        //             'instructions' => '',
        //             'required' => 0,
        //             'conditional_logic' => 0,
        //             'wrapper' => array(
        //                 'width' => '',
        //                 'class' => '',
        //                 'id' => '',
        //             ),
        //             'return_format' => 'array',
        //             'library' => 'all',
        //             'min_width' => '',
        //             'min_height' => '',
        //             'min_size' => '',
        //             'max_width' => '',
        //             'max_height' => '',
        //             'max_size' => '',
        //             'mime_types' => '',
        //             'preview_size' => 'small',
        //             'parent_repeater' => 'field_6476332c5e35d',
        //         ),
        //         array(
        //             'key' => 'field_6476332c60246',
        //             'label' => 'Product Category Title',
        //             'name' => 'product_category_title',
        //             'aria-label' => '',
        //             'type' => 'text',
        //             'instructions' => '',
        //             'required' => 0,
        //             'conditional_logic' => 0,
        //             'wrapper' => array(
        //                 'width' => '',
        //                 'class' => '',
        //                 'id' => '',
        //             ),
        //             'default_value' => '',
        //             'maxlength' => '',
        //             'placeholder' => '',
        //             'prepend' => '',
        //             'append' => '',
        //             'parent_repeater' => 'field_6476332c5e35d',
        //         ),
        //         array(
        //             'key' => 'field_6476332c6024e',
        //             'label' => 'Product Category Link',
        //             'name' => 'product_category_link',
        //             'aria-label' => '',
        //             'type' => 'link',
        //             'instructions' => 'Add the text and URL. for the first button here',
        //             'required' => 0,
        //             'conditional_logic' => 0,
        //             'wrapper' => array(
        //                 'width' => '',
        //                 'class' => '',
        //                 'id' => '',
        //             ),
        //             'default_value' => '',
        //             'maxlength' => '',
        //             'rows' => '',
        //             'placeholder' => '',
        //             'new_lines' => '',
        //             'parent_repeater' => 'field_6476332c5e35d',
        //         ),
        //     ),
        // ),
        // array(
        //     'key' => 'field_6476332c6023e',
        //     'label' => 'Shop Link',
        //     'name' => 'shop_link',
        //     'aria-label' => '',
        //     'type' => 'link',
        //     'instructions' => 'Add the text and URL. for the first button here',
        //     'required' => 0,
        //     'conditional_logic' => 0,
        //     'wrapper' => array(
        //         'width' => '',
        //         'class' => '',
        //         'id' => '',
        //     ),
        //     'default_value' => '',
        //     'maxlength' => '',
        //     'placeholder' => '',
        //     'prepend' => '',
        //     'append' => '',
        //     'parent_repeater' => 'field_6476332c5e35d',
        // ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/productcategoryshowcaseblock',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,

];