<?php

return [
	'key' => 'group_647433ce375ed',
		'title' => 'About Block',
		'fields' => array(
			array(
				'key' => 'field_647433ce39a7e',
				'label' => 'Text / Buttons',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_647433ce39a86',
				'label' => 'Heading',
				'name' => 'heading',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Add the header title here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647434807cbd1',
				'label' => 'SubHeading',
				'name' => 'subheading',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Add the sub header here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647434977cbd2',
				'label' => 'Description',
				'name' => 'description',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => 'Add the header title here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_647433ce39a94',
				'label' => 'Button',
				'name' => 'button',
				'aria-label' => '',
				'type' => 'link',
				'instructions' => 'Add the text and URL. for the first button here',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '47',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_647433ce39aa3',
				'label' => 'Background',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),

			// array(
			// 	'key' => 'field_647434f77cbd3',
			// 	'label' => 'Gradient Pattern',
			// 	'name' => 'gradient_pattern',
			// 	'aria-label' => '',
			// 	'type' => 'select',
			// 	'instructions' => '',
			// 	'required' => 0,
			// 	'conditional_logic' => 0,
			// 	'wrapper' => array(
			// 		'width' => '',
			// 		'class' => '',
			// 		'id' => '',
			// 	),
			// 	'choices' => array(
			// 		'None' => 'None',
			// 		'Green' => 'Green',
			// 		'Red' => 'Red',
			// 		'Blue' => 'Blue',
			// 	),
			// 	'default_value' => false,
			// 	'return_format' => 'value',
			// 	'multiple' => 0,
			// 	'allow_null' => 0,
			// 	'ui' => 0,
			// 	'ajax' => 0,
			// 	'placeholder' => '',
			// ),
			array(
				'key' => 'field_647433ce39aaa',
				'label' => 'Background Image',
				'name' => 'background_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => 'Add the banner image here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
                    'value' => 'acf/aboutblock',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
];